name: "Sphinx Build"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "./"
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: "DocumnetationHTML"
          path: _build/html/
 
